# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmain',
            name='TopPhoto',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
