# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0002_tripmain_topphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
