# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dayCount',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
