# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_tripmain_totalday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, choices=[('景點', '景點'), ('購物', '購物'), ('住宿', '住宿'), ('餐廳', '餐廳')], max_length=50),
        ),
    ]
