# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_auto_20160717_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, choices=[('景點', '景點'), ('購物', '購物'), ('住宿', '住宿'), ('用餐', '用餐')], max_length=50),
        ),
    ]
